import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./style.css';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;const sb=url&&key?createClient(url,key):null;
const fallback=[{id:'demo1',name_de:'BurnLab Original',name_en:'BurnLab Original',description_de:'Unsere klassische feurige Chilisauce.',description_en:'Our classic fiery chili sauce.',category:'sauce',price_cents:699,heat_level:6,stock:25},{id:'demo2',name_de:'BurnLab Inferno',name_en:'BurnLab Inferno',description_de:'Extra scharf für echte Chili-Fans.',description_en:'Extra hot for serious chili fans.',category:'sauce',price_cents:799,heat_level:10,stock:15},{id:'demo3',name_de:'BurnLab Chili-Salz',name_en:'BurnLab Chili Salt',description_de:'Würziges Salz mit Chili-Kick.',description_en:'Savory salt with a chili kick.',category:'salt',price_cents:499,heat_level:4,stock:30},{id:'demo4',name_de:'BurnLab Jungpflanze',name_en:'BurnLab Chili Plant',description_de:'Kräftige Chili-Jungpflanze.',description_en:'Healthy young chili plant.',category:'plant',price_cents:599,heat_level:3,stock:20}];
const money=n=>(n/100).toFixed(2).replace('.',',')+' €';
function App(){const[lang,setLang]=useState('de'),[products,setProducts]=useState(fallback),[cart,setCart]=useState([]),[user,setUser]=useState(null),[profile,setProfile]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState('login'),[message,setMessage]=useState(''),[admin,setAdmin]=useState(false),[busy,setBusy]=useState(false);const de=lang==='de';
useEffect(()=>{if(!sb)return;sb.from('products').select('*').eq('active',true).order('created_at').then(({data})=>data?.length&&setProducts(data));sb.auth.getSession().then(({data})=>setUser(data.session?.user));const s=sb.auth.onAuthStateChange((_,session)=>setUser(session?.user??null));return()=>s.data.subscription.unsubscribe()},[]);
useEffect(()=>{if(!sb||!user){setProfile(null);setAdmin(false);return}sb.from('profiles').select('*').eq('id',user.id).maybeSingle().then(({data})=>{setProfile(data);setAdmin(Boolean(data?.is_admin))})},[user]);
const total=useMemo(()=>cart.reduce((a,p)=>a+p.price_cents,0),[cart]);const add=p=>setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});const remove=id=>setCart(c=>c.filter(i=>i.id!==id));
async function auth(){if(!sb)return setMessage(de?'Supabase-Umgebungsvariablen fehlen.':'Supabase environment variables are missing.');setBusy(true);setMessage('');const r=mode==='signup'?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});setBusy(false);if(r.error)return setMessage(r.error.message);if(mode==='signup'&&!r.data.session)setMessage(de?'Bestätige deine E-Mail-Adresse.':'Confirm your email address.');else setMessage(de?'Erfolgreich eingeloggt.':'Signed in successfully.')}
async function checkout(){if(!sb||!user)return setMessage(de?'Bitte zuerst einloggen.':'Please sign in first.');if(!cart.length)return;setBusy(true);const totalCents=total;const o=await sb.from('orders').insert({user_id:user.id,customer_name:profile?.display_name||user.email?.split('@')[0]||'Kunde',customer_email:user.email,shipping_address:{},total_cents:totalCents}).select('id').single();if(o.error){setBusy(false);return setMessage(o.error.message)}const items=cart.map(p=>({order_id:o.data.id,product_id:p.id,product_name:de?p.name_de:p.name_en,unit_price_cents:p.price_cents,quantity:p.qty}));const r=await sb.from('order_items').insert(items);setBusy(false);if(r.error)return setMessage(r.error.message);setCart([]);setMessage(de?'Bestellung wurde gespeichert.':'Order saved successfully.')}
return <><header><a className="logo" href="#home">BURN<span>LAB</span></a><nav><a href="#home">Home</a><a href="#shop">{de?'Shop':'Shop'}</a><a href="#account">{de?'Konto':'Account'}</a><a href="#cart">{de?'Warenkorb':'Cart'} ({cart.reduce((n,p)=>n+p.qty,0)})</a></nav><button className="lang" onClick={()=>setLang(de?'en':'de')}>{de?'EN':'DE'}</button></header><main><section id="home" className="hero"><p className="eyebrow">EST. 2026 · HOT & HANDCRAFTED</p><h1>{de?'FEUER, DAS BLEIBT.':'FIRE THAT STAYS.'}</h1><p>{de?'Chilisaucen, Chilisalz und Jungpflanzen mit Charakter.':'Hot sauces, chili salt and young plants with character.'}</p><a className="cta" href="#shop">{de?'SHOP ENTDECKEN':'EXPLORE SHOP'}</a></section>
<section id="shop"><h2>{de?'UNSER SHOP':'OUR SHOP'}</h2><div className="grid">{products.map(p=><article className="card" key={p.id}><div className="flame">🌶️</div><div className="heat">{'🌶️'.repeat(Math.min(10,p.heat_level))}</div><h3>{de?p.name_de:p.name_en}</h3><p>{de?p.description_de:p.description_en}</p><strong>{money(p.price_cents)}</strong><button onClick={()=>add(p)} disabled={!p.stock}>{de?'IN DEN WARENKORB':'ADD TO CART'}</button></article>)}</div></section>
<section id="cart" className="panel"><h2>{de?'WARENKORB':'CART'}</h2>{cart.length?<><div>{cart.map(p=><div className="cartrow" key={p.id}><span>{de?p.name_de:p.name_en} × {p.qty}</span><span>{money(p.price_cents*p.qty)} <button onClick={()=>remove(p.id)}>×</button></span></div>)}</div><h3>{de?'Gesamt':'Total'}: {money(total)}</h3><button className="cta" disabled={busy} onClick={checkout}>{de?'BESTELLUNG ABSENDEN':'PLACE ORDER'}</button></>:<p>{de?'Dein Warenkorb ist leer.':'Your cart is empty.'}</p>}</section>
<section id="account" className="panel"><h2>{de?'KUNDENKONTO':'ACCOUNT'}</h2>{user?<><p>{user.email}</p><p>{de?'Angemeldet':'Signed in'}{admin?' · ADMIN':''}</p>{admin&&<a className="cta" href="#admin">ADMIN-DASHBOARD</a>}<button onClick={()=>sb?.auth.signOut()}>{de?'ABMELDEN':'SIGN OUT'}</button></>:<div className="auth"><div className="tabs"><button onClick={()=>setMode('login')}>{de?'Login':'Login'}</button><button onClick={()=>setMode('signup')}>{de?'Registrieren':'Sign up'}</button></div><input type="email" placeholder="E-Mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder={de?'Passwort':'Password'} value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={auth} disabled={busy}>{mode==='signup'?(de?'KONTO ERSTELLEN':'CREATE ACCOUNT'):(de?'EINLOGGEN':'SIGN IN')}</button>{message&&<p className="message">{message}</p>}</div>}</section>
<section id="about"><h2>{de?'ÜBER BURNLAB':'ABOUT BURNLAB'}</h2><p>{de?'Zwei junge Gründer, eine Leidenschaft: außergewöhnliche Chilis.':'Two young founders, one passion: extraordinary chilis.'}</p></section>
{admin&&<section id="admin" className="panel admin"><h2>ADMIN</h2><p>{de?'Du bist als Administrator angemeldet.':'You are signed in as an administrator.'}</p><p>{de?'Die Produkt-, Bestell-, Bewertungs- und CMS-Daten sind in Supabase geschützt.':'Product, order, review and CMS data are protected in Supabase.'}</p></section>}
</main><footer>© 2026 BurnLab. <a href="#account">{de?'Alle Rechte vorbehalten':'All rights reserved'}</a></footer></>}
createRoot(document.getElementById('root')).render(<App/>);